### ISSUE TITLE
Add tonicdev example

### ISSUE THREAD

**Issue by tolmasky** [kahliloppenheimer/text-backdrop#1]
Hi Kahlil,

Could you possibly add a tonicdev example to your package.json? I think it would be really cool to have it just work when you click 'test in your browser" from the npm page: https://www.npmjs.com/package/text-backdrop . The explanation how to do this is here: http://blog.tonicdev.com/2015/10/28/npm-plus-tonic.html

Thanks

Francisco

**Comment by kahliloppenheimer** [comment]
Hi Francisco,

I just changed the npm project so that the 'test in your browser' option works with the example I included in the README. That's actually super cool that Tonic and NPM made that integration so easy. Thanks for the heads up!
